//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskConqueror.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskConqueror.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Success.
        /// </summary>
        internal static string Action_Success {
            get {
                return ResourceManager.GetString("Action_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Task List.
        /// </summary>
        internal static string Active_Tasks_DisplayName {
            get {
                return ResourceManager.GetString("Active_Tasks_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Projects.
        /// </summary>
        internal static string Add_Projects_DisplayName {
            get {
                return ResourceManager.GetString("Add_Projects_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tasks.
        /// </summary>
        internal static string Add_Tasks_DisplayName {
            get {
                return ResourceManager.GetString("Add_Tasks_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative.
        /// </summary>
        internal static string Admin_DisplayName {
            get {
                return ResourceManager.GetString("Admin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to print report:.
        /// </summary>
        internal static string CannotPrint {
            get {
                return ResourceManager.GetString("CannotPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Goals Report.
        /// </summary>
        internal static string CompletedGoalsReport_DisplayName {
            get {
                return ResourceManager.GetString("CompletedGoalsReport_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string Delete_Confirm {
            get {
                return ResourceManager.GetString("Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Goal.
        /// </summary>
        internal static string Edit_Goal_DisplayName {
            get {
                return ResourceManager.GetString("Edit_Goal_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        internal static string Edit_Project_DisplayName {
            get {
                return ResourceManager.GetString("Edit_Project_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        internal static string Edit_Task_DisplayName {
            get {
                return ResourceManager.GetString("Edit_Task_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date cannot be earlier than Start Date.
        /// </summary>
        internal static string Error_EarlyEndDate {
            get {
                return ResourceManager.GetString("Error_EarlyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Encountered.
        /// </summary>
        internal static string Error_Encountered {
            get {
                return ResourceManager.GetString("Error_Encountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date cannot be in the future.
        /// </summary>
        internal static string Error_FutureStartDate {
            get {
                return ResourceManager.GetString("Error_FutureStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is invalid.
        /// </summary>
        internal static string Error_InvalidCategory {
            get {
                return ResourceManager.GetString("Error_InvalidCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is invalid.
        /// </summary>
        internal static string Error_InvalidStatus {
            get {
                return ResourceManager.GetString("Error_InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is missing.
        /// </summary>
        internal static string Error_MissingEndDate {
            get {
                return ResourceManager.GetString("Error_MissingEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal is missing.
        /// </summary>
        internal static string Error_MissingSelectedGoal {
            get {
                return ResourceManager.GetString("Error_MissingSelectedGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is missing.
        /// </summary>
        internal static string Error_MissingStartDate {
            get {
                return ResourceManager.GetString("Error_MissingStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is missing.
        /// </summary>
        internal static string Error_MissingTitle {
            get {
                return ResourceManager.GetString("Error_MissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run report with invalid criteria..
        /// </summary>
        internal static string Exception_CannotRunReport {
            get {
                return ResourceManager.GetString("Exception_CannotRunReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected goal and its descendents?.
        /// </summary>
        internal static string Goals_Delete_Confirm {
            get {
                return ResourceManager.GetString("Goals_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        internal static string Goals_DisplayName {
            get {
                return ResourceManager.GetString("Goals_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save an invalid goal..
        /// </summary>
        internal static string GoalViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("GoalViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new task.
        /// </summary>
        internal static string MainWindowViewModel_Command_CreateNewTask {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List tasks.
        /// </summary>
        internal static string MainWindowViewModel_Command_ListTasks {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ListTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Conqueror.
        /// </summary>
        internal static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to purge the selected object type and its descendents?.
        /// </summary>
        internal static string Objects_Purge_Confirm {
            get {
                return ResourceManager.GetString("Objects_Purge_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects have been successfully purged..
        /// </summary>
        internal static string Objects_Purge_Success {
            get {
                return ResourceManager.GetString("Objects_Purge_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated cost is invalid.
        /// </summary>
        internal static string Project_Error_InvalidEstimatedCost {
            get {
                return ResourceManager.GetString("Project_Error_InvalidEstimatedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected project and its children?.
        /// </summary>
        internal static string Projects_Delete_Confirm {
            get {
                return ResourceManager.GetString("Projects_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects_DisplayName {
            get {
                return ResourceManager.GetString("Projects_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save an invalid project..
        /// </summary>
        internal static string ProjectViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("ProjectViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Purge.
        /// </summary>
        internal static string Purge_Confirm {
            get {
                return ResourceManager.GetString("Purge_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports_DisplayName {
            get {
                return ResourceManager.GetString("Reports_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority is invalid.
        /// </summary>
        internal static string Task_Error_InvalidPriority {
            get {
                return ResourceManager.GetString("Task_Error_InvalidPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected task?.
        /// </summary>
        internal static string Tasks_Delete_Confirm {
            get {
                return ResourceManager.GetString("Tasks_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks_DisplayName {
            get {
                return ResourceManager.GetString("Tasks_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save an invalid task..
        /// </summary>
        internal static string TaskViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("TaskViewModel_Exception_CannotSave", resourceCulture);
            }
        }
    }
}
